### ISSUE TITLE
Can I use this with the sqlx feature `runtime-tokio-native-tls`?

### ISSUE THREAD

**Issue by oco-adam** [geofmureithi/apalis#113]
Hi, firstly thanks for the great library - it looks great and I'd love to use it.

I have a project in mind that I'd like to use it on, but the project is using the `sqlx` feature `runtime-tokio-native-tls` and this seems to conflict with apalis with the error: 

```
only one of ['runtime-actix-native-tls', 'runtime-async-std-native-tls', 'runtime-tokio-native-tls', 'runtime-actix-rustls', 'runtime-async-std-rustls', 'runtime-tokio-rustls'] can be enabled
```

I don't think I can easily get round this requirement  of using `sqlx` with the feature `runtime-tokio-native-tls` enabled in this particular project.

I'm fairly new to rust so sorry if I'm missing something obvious, but is it possible to use this library in a manner compatible with the `sqlx` feature `runtime-tokio-native-tls`?

**Comment by geofmureithi** [comment]
Have you tried a fine-grained approach?
```
apalis-core = { features = ["tokio-comp"], version = "0.4" }
apalis-sql = { features = ["sqlite", "migrate"], version = "0.4" }
sqlx = { features = ["runtime-tokio-native-tls"], version = "0.6"}
```

**Comment by geofmureithi** [comment]
Well this approach does not work specifically because of the timer compatibility.
The best approach now would be to use a patch via a fork.
In the next release, Executors and Timers will be combined so this problem is fixed.

**Comment by oco-adam** [comment]
Thanks very much for your reply - I can confirm that the approach that you suggested introduces new errors of the form `cannot find value sleeper in this scope`.

**Comment by geofmureithi** [comment]
For now, You can do a fork, I will work on a fix over the weekend.

**Comment by geofmureithi** [comment]
Should be sorted by #127

**Comment by geofmureithi** [comment]
@oco-adam Let me keep this open please, just for reference.
