### ISSUE TITLE
Adding a job from a nodejs process

### ISSUE THREAD

**Issue by joshbenaron** [geofmureithi/apalis#114]
How would I add a job to an apalis queue from a nodejs process?

**Comment by joshbenaron** [comment]
Also, love this package

**Comment by geofmureithi** [comment]
If you are using apalis-sql, you should be able to insert with the sql interface eg 
postgres:
```
let query = "Select apalis.push_job('apalis::Email', json_build_object('subject', 'Test apalis', 'to', 'test1@example.com', 'text', 'Lorem Ipsum'));";
```
For redis, you can check the lua:
https://github.com/geofmureithi/apalis/blob/master/packages/apalis-redis/lua/push_job.lua

Remember to format the job id correctly
https://docs.rs/apalis-core/0.4.2/apalis_core/job/struct.JobId.html

Hope that helps

**Comment by joshbenaron** [comment]
Alright, thank you. I'll close this issues, give it a go and come back and reopen issues if I have any major blockers
