### ISSUE TITLE
Redis cancel running task: worker_id?

### ISSUE THREAD

**Issue by Christof23** [geofmureithi/apalis#123]
It looks like to cancel a running task (using Redis as the queue) you need the `worker_id` and `job_id`, that latter of which can be obtained via `ctx.id()` when the task is initiated. However it's not clear how to obtain the `worker_id` associated with a running `job_id`.

**Comment by geofmureithi** [comment]
WorkerContext exposes the id:
https://github.com/geofmureithi/apalis/blob/3d214f31914e2877c966129691c846e3cc9a6810/packages/apalis-core/src/worker/mod.rs#L96-L98

You can see how to get the context here:
https://github.com/geofmureithi/apalis/blob/3d214f31914e2877c966129691c846e3cc9a6810/examples/basics/src/main.rs#L41

**Comment by Christof23** [comment]
Thanks for the help! :)
