### ISSUE TITLE
I want to buy you a coffee!

### ISSUE THREAD

**Issue by joshbenaron** [geofmureithi/apalis#124]
I might be blind but it would be cool to add a tip/"buy a coffee" etc thing in your README. I'd definitely contribute!

**Comment by geofmureithi** [comment]
Thanks! 
Well, I applied for Github sponsors, but it has been like this.
> This GitHub Sponsors profile is waiting to be reviewed by GitHub. 

Unfortunately due to my location tax policies, it may be hard to accept any tips for now.
I will update this if anything changes.
