### ISSUE TITLE
Lock-free Postgres implementation

### ISSUE THREAD

**Issue by joshbenaron** [geofmureithi/apalis#125]
Hey - what's the timeline for Lock-free Postgres implementation?

Feel free to outline the rough problem which needs to be solved and we (Bundlr) might be able to solve, depending on time commitment

**Comment by geofmureithi** [comment]
The idea behind this implementation is inspired by Que
https://github.com/que-rb/que/blob/9b264060d81f639d60bc9084ad6cc7dfb8812eba/lib/que/poller.rb#L60-L113

The full context is provided by the lib author here:
https://gist.github.com/chanks/7585810

This improvement would hopefully get postgres to 10k/s jobs from the current 1.5k/s in Github CI.
This should be straight forward porting and if combined with #126, then I expect huge performance boost.

**Comment by geofmureithi** [comment]
What are your thoughts @joshbenaron ?
