### ISSUE TITLE
Poll multiple job types on the same PostgreSQL connection

### ISSUE THREAD

**Issue by sandhose** [geofmureithi/apalis#128]
Currently, each instance of `PostgresStorage` grabs a connection to `LISTEN` for new jobs. This means that if you have 10 workers, you constantly consume 10 connections to listen on the exact same topic.

Connections can be notably expensive with Postgres, so it would be nice if multiple `PostgresStorage` could share the same notification stream (maybe through a [`tokio::sync::watch`](https://docs.rs/tokio/1.29.1/tokio/sync/watch/index.html) channel or similar?) instead of each grabbing a connection for each worker.

**Comment by geofmureithi** [comment]
This is related to #127. 
Is there a runtime agnostic suggestion you have in mind?

**Comment by sandhose** [comment]
I did a quick implementation, which is mostly copied from the `apalis-sql` implementation, using [`event-listener`](https://lib.rs/event-listener) here: 

https://github.com/matrix-org/matrix-authentication-service/blob/ca8c05ef8b87259648d1c856a2a2f36f25670184/crates/tasks/src/storage/postgres.rs#L48-L61

**Comment by arranf** [comment]
@geofmureithi This is causing issues for my usage of Apalis. Is there anything I can do to support on this issue?

**Comment by derekleverenz** [comment]
I was thinking about this too, I have ~8 job types so each has its own connection and its doing its own polling.  the ideal behavior to me would be a single connection that polls the db, and is shared by any number of Storage instances for different job types. I implmented a similar database polling tool for a different, though related task, I think its doable with something like a dedicated `PGPoller` type that is spawned as its own task and shared with various `PGStorage` instances via `Arc`, and those instances can register a job to listen for and then get notified by the poller via a channel whenever if finds a new job.

**Comment by geofmureithi** [comment]
Could you be more specific?
Which version?
As of 0.5 there is `PgNotifier` which handles the connections separately.
https://github.com/geofmureithi/apalis/blob/master/packages/apalis-sql/src/postgres.rs#L231
The stream jobs method in the current postgres implementation does not handle notifications.

**Comment by derekleverenz** [comment]
How would I share PgListen` with the `PostgresStorage`? as you say `stream_jobs` doesnt use notifications it looks like it is just polling the jobs table, so each storage instance running is doing its own polling on its own connection. What I was expecting is a way to construct a `PostgresStorage` backend with a given shared `PGListen`, and the `Backend` implementation for `PostgresStorage` would use that instead of the poll-based stream jobs (or the stream_jobs would use the notifications). Is that the work that needs to get done to enable this?

**Comment by derekleverenz** [comment]
To clarify, is there a way to use the `PgNotifier` or `PgListen` with the `PostgresStorage` backend at all currently, instead of relying on `stream_jobs` and polling postgres? (with 0.5)  And if not what do you think needs to be built/changed to support that?

**Comment by geofmureithi** [comment]
I am already working on that but it will be in 0.6 which is in the pipeline
for stability.

**Comment by geofmureithi** [comment]
@derekleverenz @arranf  checkout the postgres example in [v0.6.0-alpha.1](https://github.com/geofmureithi/apalis/tree/v0.6.0-alpha.1).
See 
https://github.com/geofmureithi/apalis/blob/732553ab731999234b164e7315f12c74a80f5a49/examples/postgres/src/main.rs#L41

**Comment by geofmureithi** [comment]
I am going to close this one, any new issues can be described in a new record.
