### ISSUE TITLE
Resolve between HasContext and JobContext

### ISSUE THREAD

**Issue by geofmureithi** [geofmureithi/apalis#130]
These APIs are conflicting and making it hard to work MQ.
https://github.com/geofmureithi/apalis-amqp/issues/1

**Comment by sadilet** [comment]
@geofmureithi Hey, nice to meet you, I've decided to use this lib to process my background tasks and rabbitmq is requirement in my case, and I need retries that is described in issue. Can I help you somehow with it? Would be perfect if you explained me what's problem in a nutshell and I would do my best to fix it.

**Comment by geofmureithi** [comment]
After investigation, I found that the bounds expected by the tower retry layer were not met. This should be fixed in 0.5.
Currently, the plausible work around would be to write a custom layer.

**Comment by sadilet** [comment]
@geofmureithi Got it, tbh i really love this crate, and if you need any help, just let me know.

Currently I'm implementing distributed rate limits(concurrent, sliding window) based on redis, once I've done I could open related PRs, and if it fitted would be great to merge.

**Comment by geofmureithi** [comment]
I need help with v0.5, documentation and creating more examples. We can discuss more. But the layers thing would be awesome too 👍🏿
