### ISSUE TITLE
Cron jobs and timezone handling

### ISSUE THREAD

**Issue by IgnisDa** [geofmureithi/apalis#136]
I have a [docker](https://github.com/IgnisDa/ryot/blob/4e18e0b0d6e83eed946edad46d2333bd9a1ad063/Dockerfile#L45) container which inherits from `scratch`. I have an apalis [cron](https://github.com/IgnisDa/ryot/blob/4e18e0b0d6e83eed946edad46d2333bd9a1ad063/apps/backend/src/main.rs#L253) job which is supposed to execute at 0000 hrs and 1200 hrs everyday. It does execute but at exactly 0530 hrs for me (I live in Asia/Kolkata timezone which has that offset). How can I configure apalis so that it executes at 0000 hrs of my timezone?

Setting the `TZ` env variable does not work, probably due to the scratch docker environment.

I'm not really sure if this problem even belongs to this repository, but would love any pointers you'd have on debugging this issue.

**Comment by geofmureithi** [comment]
Currently apalis uses UTC.
https://docs.rs/apalis-cron/latest/src/apalis_cron/lib.rs.html#108
Is it possible you play around with a custom `CronStream` implementation? And then you can comment here what you find out then we shall see what solution is possible.

**Comment by IgnisDa** [comment]
Any suggestions on how I can test it?

**Comment by geofmureithi** [comment]
I will try something and get back.

**Comment by IgnisDa** [comment]
Yes that behaviour is expected. However I'm running my application in an environment which does not have the timezone database (docker scratch).

**Comment by IgnisDa** [comment]
> Could you give this a try?
> 
> ```dockerfile
> RUN apt-get update && apt-get install -y tzdata
> ENV TZ=Your/Timezone
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> ```
> 
> Not sure it will work but just throwing it out there

Can't do this since this has to be set at build time, and I want users to be able to configure it at start-time.

> I think there is a fix that can help though. Since cron offers a chance to set the timezone,
> 
> ```rust
>    pub fn after_owned<Z: TimeZone>(&self, after: DateTime<Z>) -> OwnedScheduleIterator<Z> {
>         OwnedScheduleIterator::new(self.clone(), after)
>     }
> ```
> 
> I will offer the same functionality as [here](https://docs.rs/apalis-cron/latest/src/apalis_cron/lib.rs.html#108):
> 
> ```rust
>  pub fn to_stream_with_timezone<T: Timezone>(self) -> BoxStream { .. }
> ```

Yeah, looks good to me!

**Comment by geofmureithi** [comment]
Awesome, this should be fixed in the next release.
On another note, I want to make a list of projects using `apalis`, hope I can include [ryot](https://github.com/IgnisDa/ryot) there :)

**Comment by IgnisDa** [comment]
> Awesome, this should be fixed in the next release.

What changes would I have to make?

> hope I can include [ryot](https://github.com/IgnisDa/ryot) there :)

I would be honored!

**Comment by IgnisDa** [comment]
Cool makes sense. Thanks for your prompt response.

**Comment by IgnisDa** [comment]
Hey @geofmureithi any updates on this?

**Comment by geofmureithi** [comment]
Hopefully by the end of this month. OSS doesn't pay, I still have to pay my bills you know.

**Comment by IgnisDa** [comment]
Sorry if I came off as entitled. I understand.

**Comment by IgnisDa** [comment]
Hi @geofmureithi. Were you able to get to this?

**Comment by geofmureithi** [comment]
Here is a quick solution for your case.
```rust
trait ToStreamWithTimezone {
    fn to_stream_with_timezone(self, tz: Timezone) -> BoxStream;
}
```
Then implement it for `CronStream`.
This is a simple workaround and can unblock you until this issue is fixed. 
Let me know if this helps.

**Comment by IgnisDa** [comment]
I am not able to figure out how to use it. Is there any example?

**Comment by geofmureithi** [comment]
This is how the implementation would look:
```rust
impl<J: From<DateTime<TZ>> + Job + Send + 'static, T: Timer + Sync + Send + 'static, TZ> ToStreamWithTimezone for
    CronStream<J, T>
{
   fn to_stream_with_timezone(self, tz: TZ) -> BoxStream<'static, Result<Option<JobRequest<J>>, JobError>> {
        let stream = async_stream::stream! {
            let mut schedule = self.0.upcoming_owned(tz);
            loop {
                let next = schedule.next();
                match next {
                    Some(next) => {
                        let to_sleep = next - DateTime::<TZ>::now();
                        let to_sleep = to_sleep.to_std().map_err(|e| JobError::Failed(e.into()))?;
                        self.2.sleep(to_sleep).await;
                        yield Ok(Some(JobRequest::new(J::from(DateTime::<TZ>::now()))));
                    },
                    None => {
                        yield Ok(None);
                    }
                }

            }
        };
        stream.boxed()
    }
}
```
Let me know if it works, I haven't tested it.

**Comment by IgnisDa** [comment]
Where does `ToStreamWithTimezone` come from?

**Comment by IgnisDa** [comment]
I could not get it working: https://github.com/IgnisDa/ryot/pull/355/commits/ae2987f44545263e86fb195ee0bdaafb4c958d4c

**Comment by geofmureithi** [comment]
> I could not get it working

What was the error? Let me try to run it locally.

**Comment by IgnisDa** [comment]
I could not get generics working 
![image](https://github.com/geofmureithi/apalis/assets/60938164/a6179e3d-3eca-4b03-b57c-1038e1956b8b)

**Comment by geofmureithi** [comment]
@IgnisDa Please check if this solution works for you. #178

**Comment by IgnisDa** [comment]
@geofmureithi I was not able to figure out how to use it. I tried it with `chrono_tz::Asia::Kolkata` but it did not work.

**Comment by geofmureithi** [comment]
The compiler is telling you of a missing `From<DateTime<Tz>>` implementation here
```rust
impl From<DateTimeUtc> for ScheduledJob {
    fn from(value: DateTimeUtc) -> Self {
        Self(value)
    }
}
```

**Comment by IgnisDa** [comment]
@geofmureithi Does not work.
![image](https://github.com/geofmureithi/apalis/assets/60938164/88c4c630-31b7-4f64-a3dd-f23620afd472)
https://github.com/IgnisDa/ryot/commit/4c09f55c34201bded002718974bc0e12be640d4e

**Comment by geofmureithi** [comment]
Give it a try now.

**Comment by IgnisDa** [comment]
@geofmureithi Yep this works as expected. I think it can be merged.

**Comment by IgnisDa** [comment]
@geofmureithi Could you also publish to crates.io?

**Comment by geofmureithi** [comment]
Yeah on it

**Comment by IgnisDa** [comment]
Thank you very much for fixing this issue.

**Comment by IgnisDa** [comment]
@geofmureithi Were you able to get around to publishing it?

**Comment by geofmureithi** [comment]
#181
