### ISSUE TITLE
creating jobs from within job - pipelining

### ISSUE THREAD

**Issue by manwantnosmoke** [geofmureithi/apalis#140]
Hi, i really like the crate,

i'm looking for a way to create a pipeline, where i can post jobs from another job.
i can pass it as an Extension, but is there another way?

**Comment by geofmureithi** [comment]
Hello, is there a reason `Extension` is not enough?
You could look at https://docs.rs/tower-pipeline/latest/tower_pipeline/ but its possibly not what you want

**Comment by geofmureithi** [comment]
Related to #132
