### ISSUE TITLE
Expire Redis Keys

### ISSUE THREAD

**Issue by Christof23** [geofmureithi/apalis#149]
Hi, is there any way to add an expiry to Redis keys to avoid memory overflow?

**Comment by geofmureithi** [comment]
apalis does not have a concept of vacuuming.
I can put that in the scope of v0.5 but for now you have to do it manually rg via cron

**Comment by Christof23** [comment]
Right OK, thanks. Will look to do it manually pending 0.5 :)

**Comment by geofmureithi** [comment]
Storage introduce a vacuum method
https://docs.rs/apalis/latest/apalis/prelude/trait.Storage.html#tymethod.vacuum

You can combine this with `cron` to occasionally clean done jobs.

**Comment by iZucken** [comment]
@geofmureithi hello, I'm trying to use this crate and noticed that vacuum on redis storage does not clean up jobs in a way I expected, which effectively blocks me from using the crate as is, could you take a look at #446 ?
