### ISSUE TITLE
Postgres storage conflicts if already using sqlx

### ISSUE THREAD

**Issue by IgnisDa** [geofmureithi/apalis#177]
Since apalis postgres uses `sqlx` for migrations, it conflicts with the existing sqlx migrations I have in my project. Will it be possible to expose an option which will change the sqlx table used by apalis?

![image](https://github.com/geofmureithi/apalis/assets/60938164/d93bf1e4-7a56-470b-90c3-a05534ffdac2)

**Comment by IgnisDa** [comment]
The migration name in the screenshot is mine. I am running `sqlx::migrate!` before establishing the connection for apalis and running `setup`.

**Comment by IgnisDa** [comment]
Looking at the `migrate!` docs, I don't think it is possible to change the table name.

**Comment by geofmureithi** [comment]
Usually apalis uses its own tables and schema.
There are possible workarounds in #81

**Comment by IgnisDa** [comment]
I don't think the workarounds will work for me.

> Usually apalis uses its own tables and schema.

What does it use?

**Comment by geofmureithi** [comment]
Not sure what you are asking.

**Comment by IgnisDa** [comment]
I am aware that apalis uses the `Jobs` table. But does it use a different postgres schema? If it does then the error I am getting should not have popped up...

**Comment by geofmureithi** [comment]
It uses `apalis` schema.
https://github.com/geofmureithi/apalis/blob/42b1ab297c5b123c6b1c32a462691937c4939094/packages/apalis-sql/migrations/postgres/20220530084123_jobs_workers.sql#L1

**Comment by IgnisDa** [comment]
It creates this schema for its own tables, not for the `_sqlx_migrations` table that sqlx creates. That's why it is conflicting.

**Comment by geofmureithi** [comment]
Yeah, I am thinking of dropping sqlx and going with the native drivers or diesel. Still thinking about it.

**Comment by geofmureithi** [comment]
While the current implementation is problematic, you might get some success with this trait:
https://docs.rs/sqlx/latest/sqlx/migrate/trait.MigrationSource.html
You could in theory, import apalis migrations as `Vec<Migration>`, do the same for your migrations, merge and sort. 

See also https://github.com/launchbadge/sqlx/issues/1934

I could give it a try and see if I can crack it.

**Comment by IgnisDa** [comment]
How do I import the apalis migrations?

**Comment by geofmureithi** [comment]
If I was able to expose apalis's migrations as `Vec<Migration>` for example `apalis::migrations::postgres::migrator()`
```rust
pub struct ApalisPlusPath(Path);

impl<'s> MigrationSource<'s> for &'s ApalisPlusPath {
    fn resolve(self) -> BoxFuture<'s, Result<Vec<Migration>, BoxDynError>> {
        Box::pin(async move {
            let mut migrations = self.0.resolve().await?;
            migrations.extend(apalis::migrations::postgres::migrator()); // Append apalis migrations
            // ensure that we are sorted by `VERSION ASC`
            migrations.sort_by_key(|m| m.version);

            Ok(migrations)
        })
    }
}
```
This should work for you right?

**Comment by IgnisDa** [comment]
Yeah it should.

**Comment by geofmureithi** [comment]
I would expose it via this without the run.
https://github.com/geofmureithi/apalis/blob/42b1ab297c5b123c6b1c32a462691937c4939094/packages/apalis-sql/src/postgres.rs#L69C9-L69C46

**Comment by IgnisDa** [comment]
Alright LGTM.

**Comment by geofmureithi** [comment]
Ok I will sort you out this weekend. On the two issues.

**Comment by geofmureithi** [comment]
Please check if this helps you. #179

**Comment by IgnisDa** [comment]
@geofmureithi Yep, it works!
