### ISSUE TITLE
Add support for sqlx AnyPool

### ISSUE THREAD

**Issue by prabirshrestha** [geofmureithi/apalis#18]
Adding support for using sqlx AnyPool would allow to dynamically use any database.

**Comment by geofmureithi** [comment]
Well, I am interested in how this would work. One of the problems we would face is the logic doesn't match in each database engine. Take for example timestamps:
In sqlite it's:
```
Utc::now().timestamp()
```
While on postgres it's:
```
Utc::now()
```
There are alot of such suble differences and am not sure how to approach that in AnyPool. Please feel free to offer some more insights.
cc @autotaker

**Comment by prabirshrestha** [comment]
Would using `any_kind()` to detect and write custom logic help here?

```rust
match my_any_pool.any_kind() {
    AnyKind::Postgres => {...},
    AnyKind::Sqlite => {...},
    AnyKind::MySql => {...},
}
```

**Comment by geofmureithi** [comment]
I still think this is almost the same as using features. Unless an abstraction of storage can be created. You are possibly thinking of an ORM approach

**Comment by autotaker** [comment]
Because each storage implementation is very database-engine dependent, I think `AnyPool` approach would not work.

If you want dynamic behavior, implementing dynamic version of `Storage` trait will be better approach.

```Rust
enum AnyStorage<T> {
  Postgres(PostgresStorage<T>),
  Mysql(MysqlStorage<T>),
  Sqlite(SqliteStorage<T>),
  Redis(RedisStorage<T>),
}

impl Storage for AnyStorage<T> ... {
...
}
```

**Comment by geofmureithi** [comment]
This would be just overdoing it IMO.
The advantage of the features approach is that someone out there can create a crate called `apalis-mssql`, import `apalis-core` and  introduce MSSQL support.
