### ISSUE TITLE
Autopublish crates to crates.io

### ISSUE THREAD

**Issue by geofmureithi** [geofmureithi/apalis#19]
Right now I do it manually. It would be nice if it was automatic.
Steps needed:
1. PR to master
2. Running CI to master, must pass.
3. PR merge to master
4. Create new release
5. Publish crates to crates.io

**Comment by geofmureithi** [comment]
@autotaker If you want this one please pick it, I will try and complete the CI ASAP

**Comment by autotaker** [comment]
@geofmureithi Of course!

**Comment by autotaker** [comment]
@geofmureithi 
I have two questions.

1. How do you publish multiple packages? (Could you share the actual commands?)
2. How do you expect to automate the release procedure? Should I automate only the last step? Otherwise, what is the trigger of this release procedure?

**Comment by geofmureithi** [comment]
1. Usually the thing that matters is the order. You must start with `apalis-core` then you can follow with the rest. There is nothing special in the publish command. Just change the working directory to the package you want to publish then run `cargo publish` or in root directory you should be able to run `cargo publish -p <package name>`
Once you are done with the other packages you can now publish `apalis` itself.
Remember you could do a dry-run first to ensure it works.

2. Technically yes. The info provided is the context of how it would work. See this example https://lib.rs/crates/publish-action

Check out how some crates like sqlx do it. 
 Hope this helps.

**Comment by autotaker** [comment]
@geofmureithi 
Thank you for the information. Could you confirm my understandings?

- The trigger of release procedure is push commits on `master` that modified the version numbers in `Cargo.toml`.
  - Ignore if the same version tag is pushed already. 
- Then, GH Action automates the following steps.
  - Push a tag (e.g. `v0.4.0`) 
  - Create a release
  - Publish to each packages to crates.io  in the following order
    1. `apalis-core`
    2. `apalis-sql` `apalis-redis` `apalis-cron`
    3. `apalis`

Unfortunately, https://lib.rs/crates/publish-action does not have enough functionality. This tool does not support pushing multiple crates from single repository, nor dry-run... 
But anyway, I'll start working on this.

**Comment by geofmureithi** [comment]
I think we can rely on a new tag. When a new tag is created, we run CI, if it passed we run `cargo publish`. We can keep it simple. Then improve it later.

**Comment by autotaker** [comment]
@geofmureithi 
I have created PR: #21.
Could you review it?

**Comment by geofmureithi** [comment]
Fixed by #24
