### ISSUE TITLE
Update to sqlx 0.6

### ISSUE THREAD

**Issue by xanderio** [geofmureithi/apalis#23]
Currently `apalis-sql` is using version 0.5 of `sqlx` this make using it a bit harder than necessary to use in an application using `sqlx` 0.6.

I'm unable to use the `PostgresStorage::new` method do to the differing `sqlx` versions.

## Workaround

Pass a connection string to `PostgresStorage::connect`.

**Comment by geofmureithi** [comment]
@xanderio Are you open to submitting a PR?

**Comment by geofmureithi** [comment]
Also, this will possibly be considered into #12.
This would allow:
v 0.3 --> sqlx v0.5
v 0.4 --> sqlx v0.6
