### ISSUE TITLE
docs.rs page is broken for latest version of apalis

### ISSUE THREAD

**Issue by joshua-mo-143** [geofmureithi/apalis#236]
Hey, thanks for writing an awesome crate!

I think you may be aware already but the apalis docs.rs pages are broken for the latest builds, is this something that's likely to be fixed soon?

Thank you in advance :smile:

**Comment by geofmureithi** [comment]
This will be fixed in the 0.5 release this weekend.
The main problem is that there were alot of feature flags which have been refactored now.

**Comment by geofmureithi** [comment]
Solved by #234
