### ISSUE TITLE
shutdown_timeout 0.5.0

### ISSUE THREAD

**Issue by AzHicham** [geofmureithi/apalis#253]
Hello, 

I see that the function [shutdown_timeout](https://github.com/geofmureithi/apalis/blob/05cbe06253b7aad7f0b8b037027f3adf798a42c3/examples/basics/src/main.rs#L110) on the monitor has been removed. 
Do you plan to reintroduce it ? 
This is a very useful feature indeed, In order to let a job to finish before exiting. 

Thanks

**Comment by geofmureithi** [comment]
Ahh, I must have missed that one, let me get it back, should be straight forward.

**Comment by PainOchoco** [comment]
Bump 🙏

**Comment by geofmureithi** [comment]
@AzHicham FYI shutdown_timeout allows one to exit if the shutdown process takes longer, not to be confused with signal.
