### ISSUE TITLE
Usage of sqlx migration with postgres

### ISSUE THREAD

**Issue by xanderio** [geofmureithi/apalis#26]
It is currently not possible to use `apalis` on the same postgres database as the main application. 

This is do to the sqlx `Migrator` currently not support multiple applications using the same database. As the postgres migrations are already using a separate schema, it would be quite nice to be able to setup apalis in the same database as the main application it self.

I currently see two options: 
1. Users have to copy our migrations into there sqlx migration folder.
2. We don't use the `sqlx` migrator for postgres until `sqlx` supports mutliple applications in the same database. 

This isn't a problem for sqlite or mysql as either of these support postgresql like schemas.

See: https://github.com/launchbadge/sqlx/issues/1698

**Comment by geofmureithi** [comment]
This can be solved with an approach similar to #81
