### ISSUE TITLE
Schedule on timestamp breaking on postgres on 0.5.1

### ISSUE THREAD

**Issue by mangelarilla** [geofmureithi/apalis#275]
## Error
On calling `PostgresStorage` `schedule` method:
```
"column \"run_at\" is of type timestamp with time zone but expression is of type bigint"
```

## Context
I've imported manually all the postgres migrations  in  https://github.com/geofmureithi/apalis/tree/master/packages/apalis-sql/migrations/postgres

I did this to avoid the conflicts with my own set of migrations

I noticed there were some changes around the `Timestamp` typing, now it is an `i64` which doesn't seem to translate property into the sqlx postgres model.

Am I missing any migration?

**Comment by geofmureithi** [comment]
Not really, this is a bug. It needs the right type.

**Comment by mangelarilla** [comment]
I've created a PR, not sure if it's fully ok, postgres is not my expertise :)

**Comment by khorchanov** [comment]
Please consider also this suggestion #292
