### ISSUE TITLE
Example without code

### ISSUE THREAD

**Issue by makorne** [geofmureithi/apalis#28]
Hi! 
I found your strange example without any code.
And nobody asks about it.
 
May be I miss something and now everybody should use telepathy to use examples? :)  

[twitter-screenshot-bot](https://github.com/geofmureithi/apalis/tree/master/examples/twitter-screenshot-bot)

**Comment by geofmureithi** [comment]
Twitter API is now trash, so this is not going to happen.
https://developer.twitter.com/en/products/twitter-api
