### ISSUE TITLE
RetryLayer panic if retries set to 0

### ISSUE THREAD

**Issue by elidhu** [geofmureithi/apalis#280]
https://github.com/geofmureithi/apalis/blob/ee9b504eb15704c80507e80646f9636ed8bbbed0/src/layers/retry/mod.rs#L48

```
thread 'tokio-runtime-worker' panicked at /Users/kglasson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/apalis-0.5.1/src/layers/retry/mod.rs:48:24:
attempt to subtract with overflow
```

```
let retry = RetryLayer::new(RetryPolicy::retries(0));
```

Just an FYI, I guess it wouldn't panic in release mode, but it was a little weird!

**Comment by geofmureithi** [comment]
[Nonzero](https://doc.rust-lang.org/std/num/struct.NonZero.html) should resolve this
