### ISSUE TITLE
Extension does not work?

### ISSUE THREAD

**Issue by makorne** [geofmureithi/apalis#29]
I cant find any apalis examples with using extensions for shared data.

Only a wrong example in docs:

```
/// Extension data for jobs.
///
/// forked from [axum::Extensions]
/// # In Context
///
/// This is commonly used to share state across jobs.
///
/// ```rust,ignore
/// use apalis::{
///     Extension,
///     WorkerBuilder,
///     JobContext
/// };
/// use std::sync::Arc;
///
/// // Some shared state used throughout our application
/// struct State {
///     // ...
/// }
///
/// async fn email_service(email: Email, ctx: JobContext) {
///     let state: &Arc<State> = ctx.data_opt().unwrap();
/// }
///
/// let state = Arc::new(State { /* ... */ });
///
/// let worker = WorkerBuilder::new(storage)
///     .layer(Extension(state))
///     .build_fn(email_service);
/// ```

```

Where even  
```
use apalis::{
    Extension,
     WorkerBuilder,
     JobContext
 };
```
is throwing error `apalis does not have Extension`.

Please make a working example with Shared state.

**Comment by geofmureithi** [comment]
The redis example uses Extension.
You need to enable `extensions` in features part.
https://github.com/geofmureithi/apalis/blob/master/examples/redis/Cargo.toml#L10

**Comment by makorne** [comment]
Thank you for prompt and helpful answer!

Yes, the redis example works but the  
```
use apalis::{
    Extension,
```
is wrong, in redis example: 

```
use apalis::{
    layers::{Extension, TraceLayer},
```

And how to use apalis  for several channels for example emails with different login data A@ and B@?
 
For example 10 emails must be sent from email A@ and B@, only 1 at a time.
And if A@ is goes down they are sent from B@.

**Comment by geofmureithi** [comment]
Technically, `apalis` uses `tower` under the hood.
You can use tower trait `ServiceExt`:  https://docs.rs/tower/latest/tower/trait.ServiceExt.html eg:
```

// An async function that attempts to recover from errors returned
async fn recover_from_error(error: DbError) -> Result<Record, DbError> {
    // ...
}

// If the database service returns an error, attempt to recover by
// calling `recover_from_error`. Otherwise, return the successful response.
let mut new_service = service.then(|result| async move {
    match result {
        Ok(record) => Ok(record),
        Err(e) => recover_from_error(e).await,
    }
}
```    
You can also write your own retry layer. Or even customize your own layer.
