### ISSUE TITLE
Worker event - OutOfRangeError

### ISSUE THREAD

**Issue by rtiagom** [geofmureithi/apalis#334]
I got this error on my logs, the cron worked fine for days before. What causes it and how to debug it?
Worker event: Worker { id: WorkerId { name: "get_market_index_prices_cron", instance: Some(0) }, state: Error(Failed(OutOfRangeError(()))) }

The cron job stops running when that happens.

apalis = { version = "0.5.3", features = ["cron", "tokio-comp", "tracing", "limit"] }

**Comment by rtiagom** [comment]
The cron job stops running when that happens.

**Comment by rtiagom** [comment]
apalis = { version = "0.5.3", features = ["cron", "tokio-comp", "tracing", "limit"] }

**Comment by rtiagom** [comment]
I think this is caused when two jobs overlap. I have layer(ConcurrencyLimitLayer::new(1)) and I assumed this prevented multiple instances of the same cron job but apparently it applies to all the cron jobs being monitored. I have 13 cron jobs.
`
    let update_peers_schedule = Schedule::from_str("@weekly").unwrap();
    let update_peers_cron_worker = WorkerBuilder::new("update_peers")
        .data(CronPeersService)
        .layer(ConcurrencyLimitLayer::new(13))
        .layer(TraceLayer::new())
        .layer(RetryLayer::new(RetryPolicy::retries(100)))
        .stream(CronStream::new(update_peers_schedule).into_stream())
        .build_fn(update_peers_cron);

    Monitor::<TokioExecutor>::new()
        .register(update_symbols_cron_worker)
        .register(get_market_index_prices_cron_worker)
        .register(update_news_cron_worker)
        .register(update_forex_historical_cron_worker)
        .register(update_quarterly_fundamentals_worker)
        .register(update_fundamentals_cron_worker)
        .register(update_tickers_cron_worker)
        .register(get_new_tradable_symbols_cron_worker)
        .register(update_ratios_cron_worker)
        .register(update_ttm_fundamentals_cron_worker)
        .register(get_market_indexes_cron_worker)
        .register(update_portfolio_over_time_cron_worker)
        .register(update_peers_cron_worker)
`

**Comment by rtiagom** [comment]
What's also interesting is that when I see a Worker Event Error, I see a constant CPU usage. Usually I see a peak when the task is running and back down when it ends. 

Worker Error Event happened at 2:00.
Made some changed and recompiled and restarted at around 2:50.
<img width="688" alt="Screenshot 2024-06-09 at 3 32 44 AM" src="https://github.com/geofmureithi/apalis/assets/54023781/ffe4867a-c815-47f5-a1e0-22971c99f3a7">

**Comment by geofmureithi** [comment]
I have been trying to debug this but I could not. Could you add provide a working but crashing example? Preferably just one worker.

**Comment by rtiagom** [comment]
How many layers should I use then? Just one?

The error seems to happen only with more than one worker. A crashing example:

Worker event: Worker { id: WorkerId { name: "test_2", instance: Some(0) }, state: Start }
Running test2 at 2024-06-11 17:51:40.001502 UTC
Running test1 at 2024-06-11 17:51:45.005120 UTC
test2 completed after sleep.
Worker event: Worker { id: WorkerId { name: "test_2", instance: Some(0) }, state: Error(Failed(OutOfRangeError(()))) }
Running test1 at 2024-06-11 17:52:00.003831 UTC
Running test1 at 2024-06-11 17:52:15.004634 UTC
Running test1 at 2024-06-11 17:52:30.004614 UTC

```

use std::str::FromStr;

use anyhow::Result;
use apalis::{cron::{CronStream, Schedule}, layers::{retry::RetryPolicy, tracing::TraceLayer}, prelude::{Data, Job, Monitor, WorkerBuilder, WorkerFactoryFn}, utils::TokioExecutor};
use chrono::{DateTime, Utc};
use tokio::time::{sleep, Duration};
use tower::{limit::ConcurrencyLimitLayer, retry::RetryLayer};


#[derive(Clone)]
pub struct CronTest1Service;
impl CronTest1Service {
    async fn execute(&self, item: CronTest1Job) {
        item.run().await
    }
}

#[derive(Default, Debug, Clone)]
pub struct CronTest1Job(DateTime<Utc>);

impl CronTest1Job {
    pub async fn run(&self) {
        println!("Running test1 at {}", self.0);
    }
}

impl From<DateTime<Utc>> for CronTest1Job {
    fn from(t: DateTime<Utc>) -> Self {
        CronTest1Job(t)
    }
}

impl Job for CronTest1Job {
    const NAME: &'static str = "cron::Test1";
}

pub async fn test_cron(job: CronTest1Job, svc: Data<CronTest1Service>) {
    svc.execute(job).await;
}


#[derive(Clone)]
pub struct CronTest2Service;
impl CronTest2Service {
    async fn execute(&self, item: CronTest2Job) {
        item.run().await
    }
}

#[derive(Default, Debug, Clone)]
pub struct CronTest2Job(DateTime<Utc>);

impl CronTest2Job {
    pub async fn run(&self) {
        println!("Running test2 at {}", self.0);
        sleep(Duration::from_secs(15)).await;
        println!("test2 completed after sleep.");
    }
}

impl From<DateTime<Utc>> for CronTest2Job {
    fn from(t: DateTime<Utc>) -> Self {
        CronTest2Job(t)
    }
}

impl Job for CronTest2Job {
    const NAME: &'static str = "cron::Test2";
}

pub async fn test_2_cron(job: CronTest2Job, svc: Data<CronTest2Service>) {
    svc.execute(job).await;
}

#[tokio::main(worker_threads = 6)]
async fn main() -> Result<()> {

    let (s, ctrl_c) = async_channel::bounded(100);
    let handle = move || {
        s.try_send(()).ok();
        std::process::exit(1);
    };
    ctrlc::set_handler(handle)?;

    let test_schedule = Schedule::from_str("*/15 * * * * *").unwrap();
    let test_cron_worker = WorkerBuilder::new("test_1")
        .data(CronTest1Service)
        .layer(ConcurrencyLimitLayer::new(1))
        .layer(TraceLayer::new())
        .layer(RetryLayer::new(RetryPolicy::retries(100)))
        .stream(CronStream::new(test_schedule).into_stream())
        .build_fn(test_cron);

    let test_2_schedule = Schedule::from_str("*/5 * * * * *").unwrap();
    let test_2_cron_worker = WorkerBuilder::new("test_2")
        .data(CronTest2Service)
        .layer(ConcurrencyLimitLayer::new(1))
        .layer(TraceLayer::new())
        .layer(RetryLayer::new(RetryPolicy::retries(100)))
        .stream(CronStream::new(test_2_schedule).into_stream())
        .build_fn(test_2_cron);

    Monitor::<TokioExecutor>::new()
        .register(test_cron_worker)
        .register(test_2_cron_worker)
        .on_event(|e| {
            println!("Worker event: {e:?}");
        })
        .run_with_signal(async {
            ctrl_c.recv().await.ok();
            Ok(())
        })
        .await?;

    Ok(())
}
```

**Comment by geofmureithi** [comment]
This error seems to stem from `chrono`.
Could you check if your server is running on the same timezone as UTC.
https://github.com/chronotope/chrono/blob/de2f1f4cee53191baa15195667641c13401362ef/src/time_delta.rs#L1251

**Comment by rtiagom** [comment]
The server time is set to CEST.

**Comment by rtiagom** [comment]
I've changed DateTime<Utc> to DateTime<Local> and adjusted the scheduled to the local timezone.
```
let tz = Local::now().timezone();
...
.stream(CronStream::new_with_timezone(test_2_schedule, tz).into_stream())
```

Got the same error.

**Comment by geofmureithi** [comment]
After investigating the issue, it appears to be caused by the combination of `tokio::sleep` and `ConcurrencyLayer::new(1)`. You can view the relevant code here: https://github.com/geofmureithi/apalis/blob/27ca598f0623db04898771da314ded12691bfc5c/packages/apalis-cron/src/lib.rs#L121

As noted in [issue #251](https://github.com/geofmureithi/apalis/issues/251#issuecomment-1966609026), Apalis workers can be blocked by the tower service. In the current implementation of cron highlighted above, by the time the worker is unblocked, the next cron tick has already passed, leading to the error.

I will look into finding a workaround for this issue. In the meantime, if you need to use the `sleep` method, consider using `worker_ctx.spawn(fut);` which spawns the future without blocking.

**Comment by rtiagom** [comment]
Using worker_ctx.spawn(fut) does fix the issue in the code above but I don't use the sleep method in my production code. I have tasks that take a long time, they don't overlap with themselves but they do overlap with other running tasks. Those long running tasks have to process a lot of information and already spawn tokio tasks. 

If I understand correctly anything that can take a long time to execute should be wrapped with worker_ctx.spawn(fut) to avoid OutOfRangeError ?

**Comment by geofmureithi** [comment]
The problem you are facing is because of ConcurrencyLayer. By forcing the worker to only work on one instance of a job at a time, it means the Cron is not being polled. Why Do you need the Concurrency layer?

**Comment by rtiagom** [comment]
Apalis-cron assures only job at a time? I wasn't aware of that. Is that in the docs?

**Comment by geofmureithi** [comment]
I mean if you have a cron that runs every 15s, the stream is gonna produce one job every 15s. There is something I am missing about why you need the Concurrency layer. Can you kindly explain.

**Comment by geofmureithi** [comment]
A better question is if task 1 is still running when the cron produces a new tick, what do you want to happen? Do you want to drop it?

**Comment by rtiagom** [comment]
> A better question is if task 1 is still running when the cron produces a new tick, what do you want to happen? Do you want to drop it?

Yes. Is the concurrency layer not usable for that?

**Comment by geofmureithi** [comment]
The concurrency layer just enforces that only _n_ job is running.
In the current implementation, you cant use it with cron, cause of the failed error.
You can easily work around by using an `AtomicBool`:
- Pass an atomic bool as data.
- Then in the job execution, pull the bool from job context.
- When you receive a new tick, check if the bool is false, meaning no current job is running.
- If false use worker spawn and pass the bool there having set to true, setting it back to false when the spawned fut is complete.
- If the bool is true, it means a job is running and you can just do an early return and drop that tick.

Let me know if that helps.

**Comment by rtiagom** [comment]
Perfect, I will try that. Thanks!

**Comment by geofmureithi** [comment]
Hey @rtiagom I just realized you were looking for this.
https://docs.rs/tower/latest/tower/load_shed/index.html
You dont need the `AtomicBool` stuff, you can just use the `LoadShedLayer`

**Comment by rtiagom** [comment]
@geofmureithi Perfect! Thanks a lot for letting me know.
