### ISSUE TITLE
v0.6.0 job failures go into a continuous loop

### ISSUE THREAD

**Issue by kdesjard** [geofmureithi/apalis#372]
Job failures go into a continuous loop regardless of # of retries.

Using sqlite and for the given job, the attempts column is zero.

**Comment by geofmureithi** [comment]
Will look into it and do a patch

**Comment by geofmureithi** [comment]
@kdesjard does the current 0.6 branch work for you?

**Comment by kdesjard** [comment]
No, it still continuously loops and the db row has 0 attempts:

sqlite> select attempts,max_attempts from jobs;
0|25

**Comment by geofmureithi** [comment]
Are you using the `RetryLayer`? Could you share a minimal example?

**Comment by geofmureithi** [comment]
I think I found the bug.
Ack does not try to increase the number of attempts.
Will fix this.

**Comment by geofmureithi** [comment]
Should be resolved in #374 
The problem was ack did not update the retries.

**Comment by kdesjard** [comment]
With a retry policy of 0:

RetryLayer::new(RetryPolicy::retries(0));

A failed job runs many times (not sure if 25 or 26):

sqlite> select attempts,max_attempts from jobs;
26|25

A successful job runs once, but is the DB has 2:

select attempts,max_attempts from jobs;
2|25

**Comment by geofmureithi** [comment]
> With a retry policy of 0:
> 
> RetryLayer::new(RetryPolicy::retries(0));
> 
> A failed job runs many times (not sure if 25 or 26):
> 
> sqlite> select attempts,max_attempts from jobs;
> 26|25
> 
> A successful job runs once, but is the DB has 2:
> 
> select attempts,max_attempts from jobs;
> 2|25
> 
> 

I think there is confusion here between RetryLayer and Storage retries. RetryLayer just defines the number of in memory retries but it's still based on attempts and max_attempts. You may want to either set max_atempts or return Error::Abort to prevent retries.
