### ISSUE TITLE
Job instance that passed to the Worker function missing Task ID

### ISSUE THREAD

**Issue by BreakINbaDs** [geofmureithi/apalis#390]
Job instance can not be updated in the Worker function flow since it is missing `TaskId`

```
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct Email {
    pub to: String,
    pub subject: String,
    pub text: String,
}

impl Job for Email {
    const NAME: &'static str = "apalis::Email";
}

pub async fn send_email(job: Email) {
    log::info!("Attempting to send email to {}", job.to);
}
```

In the example above you can not successfully call `.update(job: Request<Email>)` with `job: Email` since job instance is missing `TaskId`

Is there any other way how job instance can be updated during Worker function execution flow - basically I want to update long running job progress.

**Comment by geofmureithi** [comment]
Its contained in the Data:
https://github.com/geofmureithi/apalis/blob/873a2ca322bdfe1542f3a4b1e0b3bb96b4a232ef/examples/fn-args/src/main.rs#L26
