### ISSUE TITLE
0.6.0-rc7 crashing

### ISSUE THREAD

**Issue by kdesjard** [geofmureithi/apalis#419]
After making a number of changes to get 0.6.0-rc7 to compile, I've set the storage backend as always (which includes my request type):

.backend(storage.clone())

But now I get:
```
internal error: entered unreachable code: Worker missing required context: Missing the an entry for `apalis_sql::postgres::PostgresStorage<MyType>`. Did you forget to add `.data(<apalis_sql::postgres::PostgresStorage<MyType>>)
```
Why do I need to use .data now??

**Comment by geofmureithi** [comment]
There is always something that passes through a refactor. 
I will write a quick fix

**Comment by geofmureithi** [comment]
After consideration, this will possibly be resolved internally. Here are some thoughts:
1. Adding back an implicit `Data` Layer for the backend would impose a clone for all backends which is not the case for Redis.
2. We need to standardize dependency injection, we cant inject the backend sparingly.
3. Not every job needs access the storage, I think an extra `.data(` line would not hurt your case. 

Let me know your thoughts.

**Comment by kdesjard** [comment]
Ok, if I add the storage via .data, then I get:

Worker missing required context: Missing the an entry for `apalis_core::task::task_id::TaskId`. Did you forget to add `.data(<apalis_core::task::task_id::TaskId>)

**Comment by geofmureithi** [comment]
I am updating documentation on this.
Since the introduction of `Parts`, the following are injected directly:
- `TaskId`
- `Attempt`
- `Namepace`
- `Ctx` dependent on the `Backend`

These are no longer available via `Data(T)`, just inject the directly as `T` into your job function.

**Comment by geofmureithi** [comment]
Let me know if that helps. You can also look at the `fn-args` example

**Comment by kdesjard** [comment]
Creating the worker pool:
```rust
let storage: PostgresStorage<MyReq> = PostgresStorage::new(pool.clone());

let worker = WorkerBuilder::new("MyWorker")
    .chain(|srv| srv.layer(TraceLayer::new()))
    .backend(storage.clone())
    .build_fn(execute);
```
The build_fn like the fn-args example:
```rust
pub async fn execute(
    mut proc: MyReq,
    worker_id: Data<WorkerId>,
    _worker_ctx: Context<TokioExecutor>,
    _sqlite: Data<PostgresStorage<MyReq>>,
    task_id: Data<TaskId>,
    _ctx: Data<SqlContext>,
```
then I get the crash:
```
thread 'tokio-runtime-worker' panicked at ..cargo/git/checkouts/apalis-2e5337d3a5750988/d62281f/packages/apalis-core/src/worker/mod.rs:468:45:                                                                                                                   
internal error: entered unreachable code: Worker missing required context: Missing the an entry for `apalis_sql::postgres::PostgresStorage<MyReq>`. Did you forget to add `.data(<apalis_sql::postgres::PostgresStorage<MyReq>>) 
```

**Comment by geofmureithi** [comment]
You need to do the following:
```rs
let storage: PostgresStorage<MyReq> = PostgresStorage::new(pool.clone());

let worker = WorkerBuilder::new("MyWorker")
    .chain(|srv| srv.layer(TraceLayer::new()))
    .data(storage.clone())
    .backend(storage.clone())
    .build_fn(execute);
```

And for your job fn:
```rs
pub async fn execute(
    mut proc: MyReq,
    worker_id: Data<WorkerId>,
    _worker_ctx: Context<TokioExecutor>,
    _sqlite: Data<PostgresStorage<MyReq>>, //We now include this via data
    task_id: TaskId, // TaskId Injected directly
    _ctx: SqlContext // Ctx is injected directly
)
``

**Comment by kdesjard** [comment]
With that setup I get many trait errors like:

72 |         .build_fn(execute);
   |          ^^^^^^^^ the trait `Service<apalis::prelude::Request<MyReq, SqlContext>>` is not implemented for `ServiceFn<fn(MyReq, Data<WorkerId>, Context<TokioExecutor>, Data<PostgresStorage<MyReq>>, TaskId, SqlContext) -> impl Future<Output 
= Result<OverallResult, Error>> {execute}, MyReq, SqlContext, _>`, which is required by `apalis::prelude::WorkerBuilder<MyReq, SqlContext, PostgresStorage<MyReq>, Stack<Data<PostgresStorage<MyReq>>, Stack<TraceLayer, Identity>>, _>: ap
alis::prelude::WorkerFactory<_, _, apalis::prelude::ServiceFn<_, _, _, _>>`

71 |         .backend(storage.clone())
   |          ^^^^^^^ the trait `Service<apalis::prelude::Request<MyReq, SqlContext>>` is not implemented for `ServiceFn<fn(MyReq, Data<WorkerId>, Context<TokioExecutor>, Data<PostgresStorage<MyReq>>, TaskId, SqlContext) -> impl Future<Output =
 Result<OverallResult, Error>> {execute}, MyReq, SqlContext, _>`

**Comment by geofmureithi** [comment]
Well seems I fkd up somewhere.
Looking at the [docs](https://docs.rs/apalis-core/0.6.0-rc.7/apalis_core/service_fn/trait.FromRequest.html#implementors), seems I am wrong about some of those. Looks like I missed that during the refactor. I will write a patch and clarify.

**Comment by geofmureithi** [comment]
Hey @kdesjard Please check out https://github.com/geofmureithi/apalis/pull/425 and tell me if that branch works for you.

**Comment by kdesjard** [comment]
Compiles and runs, but now the job gets stuck in the running state.

**Comment by geofmureithi** [comment]
Ok interesting. Could you try and pick a test from [here](https://github.com/geofmureithi/apalis/blob/d348630a9508d3faacea8af8a2d9ceaeb71f3a5b/packages/apalis-sql/src/postgres.rs#L567), and provide a failing test?

**Comment by kdesjard** [comment]
Is this related to https://github.com/geofmureithi/apalis/discussions/422 ?

My build_fn finishes fine, and I see job.done:

DEBUG ThreadId(06) task: apalis::layers::tracing::on_response: job.done done_in=1ms result=OverallResult { ... }

but the status does not change to Done (attempt also equals 0 ?)
```
    parts: Parts {
        task_id: TaskId(
            Ulid(
                2088692579879522513577402759446946266,
            ),
        ),
        data: Extensions,
        attempt: Attempt(
            0,
        ),
        context: SqlContext {
            status: Running,
            run_at: 2024-09-30T19:53:27.660139Z,
            max_attempts: 1,
            last_error: None,
            lock_at: Some(
                1727726007,
            ),
            lock_by: Some(
                WorkerId {
                    name: "WORKER",
                    instance: None,
                },
            ),
            done_at: None,
        },
```

**Comment by geofmureithi** [comment]
Tower consumes the request as self, so after the job is done, the parts part might need to be refreshed via `fetch_by_id`.
Where and when are you debugging the context?

**Comment by kdesjard** [comment]
I submit the job and run storage.fetch_by_id to poll the task which is where I'm debugging the context.  Even without polling, the DB still has the status as Running:
```
             id             | status  | attempts | max_attempts |            run_at             |            done_at            
----------------------------+---------+----------+--------------+-------------------------------+-------------------------------
 01J93SDK5HAJE7KGKC17XE4P6B | Running |        0 |            1 | 2024-10-01 10:18:38.130224+00 | 
```

**Comment by geofmureithi** [comment]
Ack on postgres is chucked and lazy. Can you try sleeping a second or two?

**Comment by kdesjard** [comment]
It doesn't matter if I check or not as I have two modes, sync and async, the sync requests do the polling to check for completion within a timeout period.  For async jobs, the tasks are fire and forget essentially. So, even for async jobs, the DB still has them as running even though they did complete.

**Comment by geofmureithi** [comment]
This is really interesting. I have integration tests checking this and they
are passing. I will dive more into it and get back to you.

**Comment by geofmureithi** [comment]
@ kdesjard I found the bug I was missing a critical implementation in the worker setup. Thanks for highlighting and always trying the latest version.

Basically the `AckLayer` was not being called, but now that's fixed with a test added for each storage. Please give it a try before I merge it.

**Comment by kdesjard** [comment]
Jobs are finishing now, but I'm getting trait errors if I include the TaskId in the build_fn's args.

**Comment by geofmureithi** [comment]
Could you pull the latest from the 0.6 branch and give it a try? There was some other fixes on FromRequest

**Comment by kdesjard** [comment]
All working now, thank you very much.
