### ISSUE TITLE
Can you cut a new 0.6 rc release including the bugfix in #427?

### ISSUE THREAD

**Issue by derekleverenz** [geofmureithi/apalis#429]
I saw the bug fix in  https://github.com/geofmureithi/apalis/pull/426 which is great, I'd like to use it if you publish a new rc including it

**Comment by geofmureithi** [comment]
First thing tomorrow morning.

Geoffrey Mureithi
+254713622599
mureithi.me
Skype: live:mureithinjuguna

**Comment by geofmureithi** [comment]
Resolved by #430 😄
