### ISSUE TITLE
Dynamic Job Restoration on Application Restart

### ISSUE THREAD

**Issue by anwar-al-jahwari** [geofmureithi/apalis#448]
# Dynamic Job Restoration on Application Restart

First off, thank you for the excellent work on Apalis! We've been using it in production and are very happy with its capabilities so far. However, I wanted to inquire about a specific use case.

## Context

In our production setup, we rely on Apalis for job scheduling and processing. While everything works smoothly during normal operations, we are exploring ways to ensure robust recovery in the event of an application restart (e.g., due to a deployment or crash). Specifically, we’d like to know if there is a dynamic mechanism to restore pending jobs into the queue automatically after a restart.

## Request

- **Is there already a feature or pattern in Apalis to handle this scenario?**
- **If not, would you consider adding functionality to enable dynamic restoration of pending or in-progress jobs on app startup?**

This would greatly improve the resiliency of job processing in production environments. If this feature is not yet supported, I’d be happy to contribute ideas or discuss further.

Thanks again for the great library!

**Comment by geofmureithi** [comment]
Hello, great to hear that this library is very helpful. It has taken a lot of work and lots of contributors to get here.

Regarding the recovery issue, most storages have a recovery strategy. Eg in Redis we have [reenqueue_orphaned](https://docs.rs/apalis-redis/latest/apalis_redis/struct.RedisStorage.html#method.reenqueue_orphaned) which finds tasks that are incomplete and the worker has not had a heartbeat for a specific period of time. I might need to add the time to the config but this already exists, let me know if this works for you.

**Comment by anwar-al-jahwari** [comment]
i think it will work but i wish if you can provide a small example.

**Comment by geofmureithi** [comment]
Aah I see what you are talking about, the functionality is implemented but not tied to the worker heartbeat. This is a bug and should be fixed ASAP

**Comment by geofmureithi** [comment]
In essence this should happen in the background by default.

**Comment by geofmureithi** [comment]
Currently there is a bug in the current implementation. The resuming feature is implemented but is not being called.
The solution I will offer you will look like this:
```rs
/// Config for a [RedisStorage]
#[derive(Clone, Debug)]
pub struct Config {
    poll_interval: Duration,
    buffer_size: usize,
    max_retries: usize,
    keep_alive: Duration,
    enqueue_scheduled: Duration,
    reenqueue_orphaned_after: Duration,
    namespace: String,
}
```
Now what you will be able to do is set the value when creating the storage:

```rs
let config = apalis::redis::Config::default();
config.reenqueue_orphaned_after = Duration::from_secs(30);
let storage = RedisStorage::new_with_config(conn, config);
```
This will mean that if a job has been abandoned for more than 30 secs( worker died, worker unreachable, or system restart), it will be added back to the queue.

This should solve you issue and will be applied to all backends (redis, postgres, sqlite etc).

Let me know if this fixes your issue.

**Comment by geofmureithi** [comment]
For now before the bug fix is implemented, here is an example of how to work around the issue:

```rs
fn main() {
    let config = apalis::redis::Config::default();
    let storage = RedisStorage::new_with_config(conn, config);

    // Spawn a future in the background to recover abandoned jobs
   tokio::spawn(async {
        loop {
            tokio::time::sleep(Duration::from_secs(30).await;
            // resume the oldest 100 jobs that have been abandoned for more than 60secs
            storage.reenqueue_orphaned(100, 60).await; 
        }
   })
}
```

**Comment by anwar-al-jahwari** [comment]
thanks man i really appreciate your effort. and i would like to contribute to the project. but i haven't worked in any open source project before as contributor. how i can start?

**Comment by geofmureithi** [comment]
Appreciated!
I think there is no standard way to contribute. For example reporting this but is actually contributing. You can also help with other issues and requested features. You can help improve documentation, write an article about apalis, or sponsor the project. I think the idea is start small, and dont think anything small is not appreciated.

**Comment by geofmureithi** [comment]
Yes!, this is now going to be in the next release (0.6.0-rc9).

**Comment by anwar-al-jahwari** [comment]
another question in mind what if i want to only resume jobs that are abandoned for only max of 5 mintues

**Comment by geofmureithi** [comment]
Do you mean like after 5min? Like jobs abandoned after 5mins or more? Because if you are asking if 5mins or less, it becomes hard to know which jobs that are still pending and which are abandoned.

**Comment by anwar-al-jahwari** [comment]
i meant less than 5 minutes. 
Also, when the job is considered to be not successful? 

because i want to apply the retry policy so that it will automatically retry for like 4 minutes with 5 second pause between tries. currently i am using for loop which is not ideal but it worked.

for example.

```
#[async_trait]
impl BaseJobHandler for PaymentStatusByPaymentIHandler {
    async fn handle_job(&self, job: JobType) -> Result<(), JobError> {
        match job {
            JobType::PaymentStatusByPaymentId(payment_job) => {
                let max_duration = Duration::from_secs(MAX_DURATION_SECS);
                let interval = Duration::from_secs(CHECK_INTERVAL_SECS);
                let start_time = std::time::Instant::now();

                info!(
                    msisdn = %payment_job.msisdn,
                    payment_id = %payment_job.payment_id,
                    attempt = %payment_job.attempts,
                    "Starting payment status check"
                );

                let mut interval_timer = time::interval(interval);
                let mut user_context = global_flow_manager()
                    .get_context(&payment_job.msisdn)
                    .await
                    .change_context(JobError::ProcessingError)?
                    .ok_or_else(|| error_stack::report!(JobError::ProcessingError))?;

                let mut check_count = 0u32;
               // the ugly loop
                while start_time.elapsed() < max_duration {
                    interval_timer.tick().await;
                    check_count += 1;
               }
--- the rest of the logic
```

**Comment by geofmureithi** [comment]
@anwar-al-jahwari You could use a BackoffRetryLayer, this would retry the task then wait some time if its still failing, meaning you would only care about:
```
         match state
                        .internal_services
                        .payment
                        .get_change_plan_payment_status(
                            &payment_job.msisdn,
                            &payment_job.auth_token,
                            &payment_job.order_id,
                        )
                        .await
                    {
....
```
See more conversations here: #399
