### ISSUE TITLE
Ability to add metadata

### ISSUE THREAD

**Issue by mlafeldt** [geofmureithi/apalis#450]
Hey @geofmureithi,

While integrating Apalis into a multi-tenant system where users are only supposed to retrieve the status of their own jobs, I found that attaching metadata to a job object would be beneficial. In my case, the metadata would contain user/auth-specific information. Without this feature, I'd have to add my own database table for persistence, which may or may not be encouraged.

What do you think about this?

**Comment by geofmureithi** [comment]
Hmm, this is easily doable, we can add an optional field to the context. But it would also be based on the backend and might not work on Message queues. Lets do it!

**Comment by geofmureithi** [comment]
Do you wanna work on it, or should I add it to my backlog?

**Comment by mlafeldt** [comment]
Hm, you know what? I didn't think of simply adding the metadata to the job (request) payload itself.

Kind of obvious in hindsight. 😄

**Comment by geofmureithi** [comment]
Will close this for now, we can reopen it if it comes up again

**Comment by mlafeldt** [comment]
> The problem with this solution is that it can only work for Postgres, ie using json queries.

Hey @geofmureithi,

What I meant was getting the job at runtime using `fetch_by_id`. Then, I can get whatever I serialized when creating the job.

So something like this, but in Rust via the Apalis API:

```
❯ sqlite3 -json example.db 'select * from Jobs' | jq '.[-1].job | fromjson | .client.auth_context'
{
  "authToken": "xxx",
  "resources": []
}
```

This is not limited to any database because the job payload is serialized into a string (`TEXT`).
