### ISSUE TITLE
Expose redis:aio::ConnectionManager

### ISSUE THREAD

**Issue by AzHicham** [geofmureithi/apalis#464]
Hello, 

Thank you for the v0.6.0 that's amazing job !!!! 

I wonder if it's possible to expose `redis:aio::ConnectionManager` since you are exposing the fn `connect` in apalis-redis. 
This way the ConnectionManager can be stored in a struct without re-importing the redis crate, also this will allow to never diverge in redis version (this can be painful with dependabot/renovate trying to upgrade the redis crate) 

Thank you

**Comment by geofmureithi** [comment]
Got it, should be straight forward. If you wanna do a PR that's fine
