### ISSUE TITLE
Regression: RedisStorage in v0.6.0

### ISSUE THREAD

**Issue by AzHicham** [geofmureithi/apalis#466]
Hello, 

I started to test the latest release 0.6.0 with Redis and found a regression.

I noticed that all tasks present in the redis queue `NAMESPACE:active` are fetched right away by a worker even though I'm using the following config: 
```rust
let config = Config::default()
        .set_namespace(T::BROKER_NAMESPACE_JOB)
        .set_buffer_size(1)   // **Setting a buffer size of 1 to not fetch more than a task, allowing potential other workers to fetch them**
        .set_poll_interval(Duration::from_millis(1000))
        .set_max_retries(1)
        .set_keep_alive(Duration::from_secs(120));

let product_worker_name = format!("Worker-{}-{}", T::PRODUCT_ID, random::<u32>());

let product_worker = WorkerBuilder::new(product_worker_name)
        .layer(ConcurrencyLimitLayer::new(1)) // Allow running 1 job per worker at a time
        .data(backend.clone())
        .chain(|svc| svc.check_service_clone::<Identity>())
        .backend(RedisStorage::new_with_config(
            redis_connection.clone(),
            config,
        ))
        .build_fn(handle_task::<T, HttpDispatcherClient, HttpSlideClient>);
```

I think the regression is coming from this line : 
https://github.com/geofmureithi/apalis/blob/094938d95f7ad90caab9edfc9fd04368fbcbe193/packages/apalis-redis/src/storage.rs#L482
IMO, we should have a safety here in order to not fetch from Redis in case the buffer is full ?? 
WDYT ?  

EDIT: In order to do that I think we need to use Sender/Receiver providing methode like `is_full` ? or at least `len` & `size` 
A good candidate could be [async_channel](https://docs.rs/async-channel/latest/async_channel/struct.Sender.html#method.is_full) ?

**Comment by geofmureithi** [comment]
Hmm, we might not need to use async_channel. We could just compare the worker task count with the buffer size, This would be a quick fix too. If you can apply a quick PR that would be nice, 
Another fix might be adding an atomic bool in Worker context for `is_ready`. Both would be straight forward. Let me know your thoughts.

**Comment by AzHicham** [comment]
I'll try that ;)

**Comment by AzHicham** [comment]
TBH I don't know how to connect the `task_count` to `buffer_size`. 

I can set a cond like this `worker.task_count() == 0` then fetch from redis. 
This is nice in my case because I have a `buffer_size` of 1 and I use a `ConcurrencyLimitLayer::new(1)` but in the case 
I have a `ConcurrencyLimitLayer::new(10)` for instance I don't want the `task_count` to reach 0 before fetching new tasks from Redis

**Comment by AzHicham** [comment]
I think the perfect solution if to have a cond like this: 

```rust
// We need to get remaining free spot in the buffer if the buffer is not full pull 'free_spots' tasks
let free_spots = self.buffer_size - tx.len(); 
if free_spots > 0 {
    let res = self.fetch_next(worker.id(), free_spots).await; // change fetch_next with an additional arg
    ...
}
```

But if you have a better idea I'll take it ;)

**Comment by geofmureithi** [comment]
`ConcurrencyLimitLayer::new(10)` just means the worker cannot be executing more than 10 tasks at a time. 
Our goal here is that we need not to fetch when the service is not ready. This was the previous behavior. But currently we are using `tower::CallAll` which is possibly why consuming everything, coz the stream is being consumed to the end. 
In all essence, we should use `ConcurrencyLayer` rather than buffer size. Buffer size is specific to redis and is about how many jobs to fetch at a time. I think I have some ideas on how to get this behavior back, let me write something tonight and we can discuss it tomorrow.

**Comment by AzHicham** [comment]
OK thanks for your help !!!

**Comment by AzHicham** [comment]
The thing I don't clearly understand if the definition of `is_ready` for me it's: 
Is the worker able to start this task ? This may depend on ConcurrencyLimitLayer.

Indeed if instead of `tower::CallAll` we can use another mecanisme in order to not start task until the work is_ready eg able to start new task then it should solve this issue

**Comment by geofmureithi** [comment]
Meanwhile, could you check something for me?
Modify the `tower::CallAllUnordered` to `tower::CallAll` in `Worker::poll_jobs` in `apalis-core` and see if it works

**Comment by geofmureithi** [comment]
> EDIT: IMO buffer_size should not be specific to redis.

I should have said its backend specific since some backends like messagequeues already handle this for themselves.
Workers just take `Stream` and consume them. To control this from a worker perspective, you need to use `ConcurencyLayer`

**Comment by AzHicham** [comment]
> Meanwhile, could you check something for me?
> Modify the `tower::CallAllUnordered` to `tower::CallAll` in `Worker::poll_jobs` in `apalis-core` and see if it works

Same behavior with tower::CallAll. All tasks are fetched from `active` and put into `inflight` :/

**Comment by geofmureithi** [comment]
Ok, I already have something in mind. Hopefully its a single change :). Give me a few hrs

**Comment by AzHicham** [comment]
Hello,

Still not working, but I think you forget to push some changes ? Because on this branch I only see the layer, but not how the AtomicBool is updated

**Comment by geofmureithi** [comment]
I need you to do something like:
```
if worker.is_ready() {
  fetch_next().await
}
```
In redis storage. Are you sure its not working?

**Comment by AzHicham** [comment]
It's getting better, with : 
```rust
is_ready: Arc::new(AtomicBool::new(true)),
```
and
```rust
if worker.is_ready() {
  fetch_next().await
}
```
Fetch occurs only when the worker is not busy.
But still with a buffer_size of 1, a task is fetched will the worker is running. 
Eg: 
I push 3 tasks.
1 task is launched (concurrency still limited to 1)
1 task is i think the buffer 
1 is in the redis active queue

**Comment by geofmureithi** [comment]
Good!, I might need to use `load(Acquire)` this may fix it. But we are headed there.

**Comment by AzHicham** [comment]
Another weired behaviour but may be I'll open another dedicated issue is when I send a SIGTERM/SIGINT while using this code: 
```rust
...
monitor.run_with_signal(shutdown_signal()).await?;

pub(crate) async fn shutdown_signal() -> Result<(), io::Error> {
    let mut sigterm = sigterm();
    let mut sigint = sigint();
    select! {
        biased;
        _ = sigterm.recv() => info!("SIGTERM signal. Exit now !!"),
        _ = sigint.recv() => info!("SIGINT signal. Exit now !!"),
    }
    Ok(())
}
```

Then the worker finish to handle all tasks and then exit, even the tasks that is still in the Redis active queue. (Following my previous comment all 3 tasks are done)

**Comment by geofmureithi** [comment]
Hey, I think this has been resolved with the current push.

**Comment by geofmureithi** [comment]
Also I have created this issue https://github.com/tower-rs/tower/issues/801 which would also relates to this.

**Comment by geofmureithi** [comment]
Lol, look at what I did:
```
    /// Start running the worker
    pub fn start(&self) {
        self.state.running.store(false, Ordering::Relaxed);
        self.state.is_ready.store(false, Ordering::Relaxed);
        self.emit(Event::Start);
    }
    ```
Start sets it to false 😢

**Comment by AzHicham** [comment]
haha thx I'll test against the fix ;)

**Comment by AzHicham** [comment]
Everything works as expected !!! 

My test: 
- Push 3 tasks on redis queue
- start a worker -> 1 job is launched against the 1st task. 
- before the end I send a SIGTERM. 
- the job finish then the worker shutdown.
- In Redis I still have 2 tasks remaining. 
- I re-launch a worker and anothe job is launched against the 2nd task. 

Nothing to say expect, Good job !!!! 

Thanks for your help !!

**Comment by AzHicham** [comment]
Hello @geofmureithi 

Sorry to bother you, I just wanted to know when you're gonna release a patch version ? 

Thank you
