### ISSUE TITLE
New features 

### ISSUE THREAD

**Issue by AzHicham** [geofmureithi/apalis#47]
Hello 

First of all thanks for your amazing work !! 
Here are some features that could be really amazing 

- Composition / Pipeline like in [Dramatiq](https://dramatiq.io/cookbook.html#composition), or may be add a way to send a task B within a task A
- Handle sigterm signal and do a warm shutdown eg stop listening for more jobs and wait for active job to finish
- Add priority to message handling 
- Is there a way to do some unit testing with mocking or a stub (eg without running a Redis for example)

Few questions btw, does a worker run in a dedicated thread ? 
Is it possible to run multiple instance of worker app ?

**Comment by geofmureithi** [comment]
Hello
So, some of the issues you have raised will be covered in version 0.4 (#12)  specifically pipe-lining and shutting down.
On priority handling, It is currently not a major priority, as one can achieve this by running multiple workers or other workarounds.
On the issue of testing, there will be improvements in v0.4, but we may also add `MockStorage`.

On the other questions:
- does a worker run in a dedicated thread ? No, workers are run on a tokio thread pool
- Is it possible to run multiple instance of worker app ? Yes, depending on what you are asking, eg `register_with_count` for multiple workers, run multiple process (apart from cron), or run multiple machines(apart from sqlite & cron)

**Comment by AzHicham** [comment]
Hi

Thats really cool for pipe-lining, shutting down and mocking !! For priority I understand there is plenty of ways to do it, with multiple worker for instance ! 

- Ok, As long as we can limite the number of concurrent worker that's fine !! I tried and it works fine !! 
- I did a simple test with  1 client + 2 application worker (eg simulate scaling in kubernetes) and It works like a charm !! 

Thanks a lot !!

**Comment by AzHicham** [comment]
Hello @geofmureithi  Idk if you saw my last edit about a potential bug when Redis restart while worker is already connected :)

**Comment by geofmureithi** [comment]
Hey, can you create an issue with the steps to replicate this?

**Comment by geofmureithi** [comment]
Hey @AzHicham Does #54 Fix your issues?

**Comment by AzHicham** [comment]
Sorry for the late reply 
I'll try this asap :)
