### ISSUE TITLE
use column names in sql inserts

### ISSUE THREAD

**Issue by kdesjard** [geofmureithi/apalis#474]
I would like to be able to extend the jobs table with additional columns (instead of having to join to other tables etc).  I believe all of the sql except for the INSERTs should work.

Eg, from:
```
let query = "INSERT INTO apalis.jobs VALUES ($1, $2, $3, 'Pending', 0, $4, NOW() , NULL, NULL, NULL, NULL)";
```
To:
```
let query = "INSERT INTO apalis.jobs
(job,id,job_type,status,attempts,max_attempts,run_at,last_error,lock_at,lock_by,done_at)
VALUES ($1, $2, $3, 'Pending', 0, $4, NOW() , NULL, NULL, NULL, NULL)";
```
Or would it best to implement a custom backend?

**Comment by geofmureithi** [comment]
I am open to a PR as long as it doesn't break anything.

**Comment by kdesjard** [comment]
I ended up implementing my own storage.
