### ISSUE TITLE
Is there a way to send dependencies to jobfunction

### ISSUE THREAD

**Issue by akhildevelops** [geofmureithi/apalis#79]
Hi Thanks for sharing this excellent library to the community.

Currently the job function accepts two arguments: one is Request type and JobContext

I want to share database pool connection to my job function, is there a way I can do it ?

Example:

```rust
#[derive(Deserialize, Serialize)]
struct Youtubelink(String);

impl Job for Youtubelink {
    const NAME: &'static str = "youtube-transcript";
}

async fn transcript(
    job: impl Into<Youtubelink>,
    ctx: JobContext,
    // pgpool: &PgPool
) -> Result<YoutubeContent, Serror> {
    let data = Youtube::link(&job.into().0).content().await?;
    // do something with pgpool and data
}
```
I'm looking something like this where [dbpool](https://github.com/actix/examples/blob/866ad278d5127bc25cdb47c0caf93317f39900a7/databases/postgres/src/main.rs#L126) is created and registered. Later used in [handlers](https://github.com/actix/examples/blob/866ad278d5127bc25cdb47c0caf93317f39900a7/databases/postgres/src/main.rs#L91)

**Comment by geofmureithi** [comment]
There is already a way to do this

https://github.com/geofmureithi/apalis/blob/2079bb178c3413b6802ac0127bb91a5d93ec87c8/examples/using-context/src/main.rs#L101-L105

**Comment by akhildevelops** [comment]
Thanks 👍
