### ISSUE TITLE
Add documentation and examples of how workers process jobs

### ISSUE THREAD

**Issue by prabirshrestha** [geofmureithi/apalis#8]
Currently it only shows one worker `send_email`. Would be good to showcase more types of jobs being consumed.

```rust
    Monitor::new()
        .register_with_count(5, move |_| {
            WorkerBuilder::new(sqlite.clone())
                .layer(TraceLayer::new())
                .build_fn(send_email)
        })
        .run()
        .await
```

**Comment by geofmureithi** [comment]
Do you mean something like this [example](https://github.com/geofmureithi/apalis/blob/master/examples/rest-api/src/main.rs#L320)?

**Comment by prabirshrestha** [comment]
Yes. Could you explain what register_with_count does? In the example the total equals 9. Is this number of dedicated threads or is this queued in a thread pool. Clarifying how workers work in README would be great.

**Comment by geofmureithi** [comment]
The correct answer is a thread pool, but I understand that we may need to add some more docs and maybe diagrams illustrating how these work.
