### ISSUE TITLE
 emit logs and error messages 

### ISSUE THREAD

**Issue by akhildevelops** [geofmureithi/apalis#80]
It's difficult to check the error messages from db on job failures.

Let the workers emit logs to stdout and stderr.

**Comment by geofmureithi** [comment]
Have you tried using tracing crate?

**Comment by akhildevelops** [comment]
Nope.

**Comment by geofmureithi** [comment]
Please use the example below:
https://github.com/geofmureithi/apalis/blob/cdcf5276c2df93dce8c51ab25d99a4d98ca01de7/examples/tracing/src/main.rs#L31-L35

**Comment by geofmureithi** [comment]
Please also remember to use `tracing` feature, set `RUST_LOG` and add `.layer(TracingLayer::new)`
