### ISSUE TITLE
Fails to run, if there's a migrations folder in the project root

### ISSUE THREAD

**Issue by akhildevelops** [geofmureithi/apalis#81]
I have my own migrations folder in the root of the project. Apalis fails to run workers on database migration error.

```rust
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/controller`
Error: Database("migration 20230420060200 was previously applied but is missing in the resolved migrations")
```
Note `20230420060200` is my project's migration file.

**Comment by akhildevelops** [comment]
I've fixed it by ignoring missing migration files  by modifying https://github.com/geofmureithi/apalis/blob/b3107e0fef6319fa54ad2cd8156102b0a2c807f0/packages/apalis-sql/src/postgres.rs#L65-L70 to:
```rust
#[cfg(feature = "migrate")]
    pub async fn setup(&self) -> Result<(), sqlx::Error> {
        let pool = self.pool.clone();
        let mut migrator = sqlx::migrate!("migrations/postgres");
        migrator.ignore_missing = true;
        migrator.run(&pool).await?;
        Ok(())
    }
```

**Comment by akhildevelops** [comment]
Lemme know if this fix helps, I'll give a PR @geofmureithi

**Comment by geofmureithi** [comment]
Please do the PR 💪🏿

**Comment by akhildevelops** [comment]
Hi @geofmureithi, gave the PR lemme know if it's ok ?

**Comment by geofmureithi** [comment]
Your PR is ok, though it only covers postgres. I haven't had time to test it yet. I also need to figure out what to add in the docs about this.

**Comment by akhildevelops** [comment]
Specific to this change, need not add anything as this doesn't directly affect the user of apalis.

**Comment by geofmureithi** [comment]
I am thinking, instead of doing it this way, why cant the user just create their own migrator?
````rust
trait MyMigrator {
    async fn migrate(&self) -> Result<(), sqlx::Error>;
}
impl MyMigrator for PostgresStorage {
    async fn migrate(&self) -> Result<(), sqlx::Error> {
        let pool = self.pool.clone();
        let mut migrator = sqlx::migrate!("migrations/postgres");
        migrator.ignore_missing = true;
        migrator.run(&pool).await?;
        Ok(())
    }
}

````

**Comment by akhildevelops** [comment]
This is doable. I would suggest, this should be fixed at upstream (i.e, apalis). Users would definitely get this issue if they are using common database for apalis and their application.

I believe your concerns are for other databases right ?

**Comment by geofmureithi** [comment]
The point of this approach is that we don't need to change any of the current workings. Because the user can do it without needing to make the change the current source. Apalis doesn't care how you do your migrations, as long as the db is valid.
For now I will close this issue because it's specific to certain users and there is a workaround suggested.

**Comment by akhildevelops** [comment]
I've just tried to implement as per this suggestion: https://github.com/geofmureithi/apalis/issues/81#issuecomment-1528826392

I'm facing two problems, one I need to use `async-trait` crate for declaring async trait functions (this can be resolved) and second `self.pool` is not accessible as it's private.

**Comment by akhildevelops** [comment]
There could be one more problem in the line `let mut migrator = sqlx::migrate!("migrations/postgres");`, in sqlx::migrate!(<dir>), the <dir> is a relative path and [gets combined with a basepath obtained by `CARGO_MANIFEST_DIR`](https://github.com/launchbadge/sqlx/blob/6be16b4d1b55b20985b8b762956ab443f9481c3d/sqlx-macros/src/common.rs#L28), as the user's application doesn't have `migrations/postgres` folder, the user app might fail.

Refer: https://github.com/rust-lang/cargo/issues/8397

**Comment by akhildevelops** [comment]
I understand that this problem is confined only to me, therefore I've modified apalis and have been using for myself.
Once again thanks for this amazing tool.

**Comment by geofmureithi** [comment]
> the is a relative path and ...

This can be disabled by disabling migrate feature and doing it yourself.

> `self.pool` is not accessible as it's private.
This will be fixed in the next release
